### ISSUE TITLE
`timeouts.Block` causes error in modify plan set

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-plugin-framework-timeouts#14]
### Terraform CLI and Framework Versions

github.com/hashicorp/terraform-plugin-framework v0.16.0
github.com/hashicorp/terraform-plugin-framework-timeouts v0.2.0

### Terraform Plugin Framework Code

```golang
func (r *resourceTable) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	schema := tfsdk.Schema{
		Attributes: map[string]tfsdk.Attribute{
			// ...
		},
		Blocks: map[string]tfsdk.Block{
			// ...
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Update: true,
				Delete: true,
			}),
		},
		Version: 1,
	}

	return schema, nil
}
```

### Terraform Configuration

```terraform
resource "aws_dynamodb_table" "test" {
  name           = "test"
  read_capacity  = 1
  write_capacity = 1
  hash_key       = "test"

  attribute {
    name = "test"
    type = "S"
  }
}
```

### Expected Behavior

In a debugging session or provider acceptance tests, I should reach the `Create` function

### Actual Behavior

I get an error like

> Error running pre-apply refresh: …
> Error: Error modifying plan …
> AttributeName(“timeouts”): couldn’t find attribute in resource schema: path leads to block, not an attribute

when running provider acceptance tests

### Steps to Reproduce

Run provider acceptance test

### Additional Information

I am trying to port the AWS Provider resource [`aws_dynamodb_table`](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/dynamodb/table.go), so we have to use the Block version of the timeouts.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment]
Hey Graham 👋 

Sorry for the delay in getting to this and apologies that you ran into an issue here.

I've opened a PR to [Amend Plan Resource Change To Allow For Optional Blocks](https://github.com/hashicorp/terraform-plugin-framework/pull/552#top) on _terraform-plugin-framework_ to address this but will judge from the feedback as to whether the proposed fix is acceptable.
