### ISSUE TITLE
Import timeout attribute panic

### ISSUE THREAD

**Issue by phillebaba** [hashicorp/terraform-plugin-framework-timeouts#46]
### Terraform CLI and Framework Versions

terraform-plugin-framework: v1.2.0

### Terraform Plugin Framework Code

```golang
func (r *bootstrapGitResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
        resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"timeouts": timeouts.AttributesAll(ctx),
		},
	}
}


func (r *bootstrapGitResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	data := bootstrapGitResourceData{}
	data.ID = types.StringValue(req.ID)
	data.Namespace = data.ID
	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}
```

### Terraform Configuration

```terraform
resource "flux_bootstrap_git" "this" {}
```

### Expected Behavior

I expect the import to succeed without any errors or panics.

### Actual Behavior

After implementing the timeout attributes acceptance tests which are validating import started failing with a panic. 

```
panic: AttributeName("timeouts"): can't use tftypes.Object[] as tftypes.Object["create":tftypes.String, "delete":tftypes.String, "read":tftypes.String, "update":tftypes.String]
```

This is probably due to the fact that the empty timeout object is missing the attributes.

### Steps to Reproduce

1. `terraform apply`

### Additional Information

This error occurred when trying to implement a timeout attribute. I guess one solution would be to set each attribute individually in the state instead of writing the whole object. I think it might be better to document a good way to create an empty timeout object with the expected attributes defined in the scheme.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phillebaba** [comment]
I checked the version and I am using `v0.3.1`, have I done something wrong in the code? I followed the examples in the documentation. I went with using nested attributes instead of blocks because that is what other docs states is the preferred type for new attributes.

https://developer.hashicorp.com/terraform/plugin/framework/resources/timeouts

I also checked that the unmarshalled value is `timeouts.Value`. It seems like all of my other tests are passing except the import tests. So I think the issue is related only to importing.

**Comment by bendbennett** [comment]
@phillebaba thank you for confirming you're using the latest version of `terraform-plugin-framework-timeouts`.

Could you share the code for one of the tests that produces a panic?

Using the following resource and configuration, running `terraform import timeouts_example.example example-id` followed by `terraform apply` completes successfully.

```go
package provider

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = (*exampleResource)(nil)
var _ resource.ResourceWithImportState = (*exampleResource)(nil)

func (r *exampleResource) Schema(ctx context.Context, request resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "Example resource",

		Attributes: map[string]schema.Attribute{
			"configurable_attribute": schema.StringAttribute{
				MarkdownDescription: "Example configurable attribute",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Example identifier",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
			}),
		},
	}
}

func NewResource() resource.Resource {
	return &exampleResource{}
}

type exampleResourceData struct {
	ConfigurableAttribute types.String   `tfsdk:"configurable_attribute"`
	Id                    types.String   `tfsdk:"id"`
	Timeouts              timeouts.Value `tfsdk:"timeouts"`
}

type exampleResource struct {
	provider playgroundProvider
}

func (r *exampleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_example"
}

func (r *exampleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data exampleResourceData

	diags := req.Plan.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, 20*time.Minute)

	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Info(ctx, fmt.Sprintf("%v", createTimeout))

	_, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	data.Id = types.StringValue("example-id")

	tflog.Trace(ctx, "created a resource")

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}

func (r *exampleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data exampleResourceData

	diags := req.State.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	t, diags := data.Timeouts.Read(ctx, 20*time.Minute)

	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Info(ctx, fmt.Sprintf("timeout = %s", t.String()))

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}

func (r *exampleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
}

func (r *exampleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
}

func (r *exampleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
```

With the following configuration:
```terraform
resource "timeouts_example" "example" {
  configurable_attribute = "some-values"
  
    timeouts = {
      create = "60m"
      read = "30m"
    }
}
```

**Comment by phillebaba** [comment]
My understanding of the timeouts attribute is that it is optional. What would happen if the nested attribute was not defined and import was run.

The test that is failing is defined here.

https://github.com/fluxcd/terraform-provider-flux/blob/74ad8329243d0bd218b463ade0ab5e0636296350/internal/provider/resource_bootstrap_git_test.go#L135-L141

This test defines configuration from the following template. As you can see the timeout block is not defined.

```
provider "flux" {
  kubernetes = {
    config_path = "%s"
  }
  git = {
    url = "%s"
    http = {
      username = "%s"
      password = "%s"
      allow_insecure_http = true
    }
  }
}
  
resource "flux_bootstrap_git" "this" {
  toleration_keys = ["FooBar", "test"]		
}
```

One thing to note is that my import logic does not only pass through the id but sets other attributes to the state. Which causes it to crash when writing to the state.

https://github.com/fluxcd/terraform-provider-flux/blob/74ad8329243d0bd218b463ade0ab5e0636296350/internal/provider/resource_bootstrap_git.go#L878

**Comment by bendbennett** [comment]
@phillebaba thank you for supplying the details of a test that is causing a panic.

It looks like the panic is a result of a mismatch between the schema, and value that is being saved into the state in the `ImportState()` func. 

Explicitly setting the value of `timeouts` in the `ImportFunc()` should prevent the panic, for example:

```go
func (r *bootstrapGitResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	data := bootstrapGitResourceData{}
	data.ID = types.StringValue(req.ID)
	data.Namespace = data.ID
	data.Timeouts = timeouts.Value{
		Object: types.ObjectNull(map[string]attr.Type{
			"create": types.StringType,
			"delete": types.StringType,
			"read":   types.StringType,
			"update": types.StringType,
		}),
	}

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}
```

**Comment by bendbennett** [comment]
@phillebaba we have discussed this a little further and a couple of alternate suggestions were made.

In order to avoid explicitly setting `timeouts` you could alter the `ImportState()` function to use `resp.State.SetAttribute()` on the attributes you need to set rather than calling `resp.State.Set()`. For instance:

```go
func (r *bootstrapGitResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	id := types.StringValue(req.ID)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
	if resp.Diagnostics.HasError(){
		return
	}
	...
}
```

Alternatively, you could populate `data.Timeouts` as follows:

```go
func (r *bootstrapGitResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	data := bootstrapGitResourceData{}
	data.ID = types.StringValue(req.ID)
	data.Namespace = data.ID
	
	var timeouts timeouts.Value
	resp.Diagnostics.Append(resp.State.GetAttribute(ctx, path.Root("timeouts"), &timeouts)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.Timeouts = timeouts

	diags := resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}
```

If you wish to track this issue it has been documented in [Missing/Null Object During State Setting Causes Panic With Missing Attribute Types](https://github.com/hashicorp/terraform-plugin-framework/issues/566#top)

**Comment by phillebaba** [comment]
Great thanks, I might change to use the second option instead. The tests pass now as the scheme is correct. Thank you for the help!
