### ISSUE TITLE
timeouts/schema.go - documentation 

### ISSUE THREAD

**Issue by jbinko** [hashicorp/terraform-plugin-framework-timeouts#51]
### Terraform CLI and Framework Versions

1.4.5

### Use Cases or Problem Statement

Below is output of go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs
if you specify in schema timeouts attribute
"timeouts": timeouts.AttributesAll(ctx),

Output:
======
Nested Schema for timeouts
Optional:

create (String)
delete (String)
read (String)
update (String)
======

### Proposal

It's not nice. I believe if we change timeouts/schema.go and for each create/delete/read/update attribute specify generic Description field like "(Defaults to XX minutes) Used when creating the resource." it will provide better results and will save time to developers.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment]
Hi @jbinko 👋 

Thank you for the feedback. I think that your suggestion of modifying the `Description` fields will yield a more informative user experience. A PR along these lines will be forthcoming.
